Algorithm for sampling from an arbitrary GI
CDCgov/ixa-epi-isolation pull request #24
Opened 2024-12-04 23:17 UTC by ChiragKumar9

### Overview

This PR implements the use of order statistics to draw sequential infection times from an arbitrary GI and testing the algorithm. The algorithm is described in detail in #19.

### Feedback requested

1. I focus on testing the validity of the algorithm, but any suggestions for further tests are welcome
2. Thoughts on how to further generalize the sampling approach to be robust to interventions/changes to the GI?
3. Ways to improve efficiency?

### Not addressed

This PR still assumes that the GI is an exponential distribution. This is assumed in both the code and the tests. Our next step is to implement a function for a different GI -- the triangle VL curve from our isolation work -- and use that with person-specific parameters.

2024-12-05 19:41 UTC, ekr-cfa requested changes
You're going to need to rebase this on origin/main.

2024-12-05 19:41 UTC, ekr-cfa commented on src/transmission_manager.rs
> +        assert!(ks_stat < 1.44 / f64::sqrt(f64::from(n_iter)));
You should factor this out as in PR#26

2024-12-06 15:16 UTC, ekr-cfa commented on src/transmission_manager.rs
> +            // Finally, we need one more helper function. The contact experiences a full infectious course.
How is this a helper function?

2024-12-06 15:16 UTC, ekr-cfa commented on src/transmission_manager.rs
> +            // We add the contact to the context _after_ we choose the transmitter (happens in init).
Because why? So that you don't choose the contact as the infected person?

2024-12-06 15:16 UTC, ekr-cfa commented on src/transmission_manager.rs
> +                move |context, event: PersonPropertyChangeEvent<InfectiousStatus>| {
Can you coalesce this with the event handler in `record_infection_times`?

2024-12-06 19:15 UTC, ekr-cfa approved these changes
LGTM

2024-12-06 23:00 UTC, confunguido requested changes

2024-12-06 23:00 UTC, confunguido commented on src/transmission_manager.rs
>              let mut context = setup(1.0);
Is there a reason for an `r0` of 1.0? Wouldn't that result in only one infection attempt? Am I misunderstanding anything?

2024-12-06 23:00 UTC, confunguido commented on src/transmission_manager.rs
>              let mut context = setup(1.0);
Is there a reason for an `r0` of 1.0? Wouldn't that result in only one infection attempt? Am I misunderstanding anything?

2024-12-09 15:21 UTC, confunguido approved these changes

2024-12-10 17:12 UTC, merged