Update ixa - Closes issue #28
CDCgov/ixa-epi-isolation pull request #32
Opened 2024-12-18 21:59 UTC by confunguido

As described in issue #28, removed unnecessary module name in ixa imports, updated main to use ixa runner with custom args, and use `sample_person`. A couple of things to highlight:
1) sample_person does not yet allow to filter by a person property, so making a safe assumption here that everyone is alive at time t = 0.
2) It's a bit confusing to use custom_args for boolean values. For instance, I used the `force_overwrite` flag to determine whether or not to overwrite reports. If not specified, I would assume the value is false, but if not specified, `custom_args` would not exist, so I still need to do `if let Some(custom_args) = custom_args {}else{}`, which seems a bit unnecessasry.

2024-12-18 22:00 UTC, confunguido commented
I can see that my tests aren't working, probably pre-commit issue. Working on fixing that.

2024-12-18 23:08 UTC, ekr-cfa commented
I just added `sample_person()` with a query

2024-12-19 13:39 UTC, confunguido commented
> I just added `sample_person()` with a query

Thanks! Just updated the code.

2024-12-19 13:40 UTC, confunguido commented
> As described in issue #28, removed unnecessary module name in ixa imports, updated main to use ixa runner with custom args, and use `sample_person`. A couple of things to highlight:
> 
> 1. sample_person does not yet allow to filter by a person property, so making a safe assumption here that everyone is alive at time t = 0.
> 2. It's a bit confusing to use custom_args for boolean values. For instance, I used the `force_overwrite` flag to determine whether or not to overwrite reports. If not specified, I would assume the value is false, but if not specified, `custom_args` would not exist, so I still need to do `if let Some(custom_args) = custom_args {}else{}`, which seems a bit unnecessasry.

All my initial comments about `sample_person` and custom boolean args have been solved with ixa updates.

2024-12-19 21:03 UTC, ChiragKumar9 commented on src/main.rs
>      /// whether force overwrite of output files if they already exist
```suggestion
    /// Whether to force overwrite of the output files if they already exist.
```

2024-12-19 21:05 UTC, ChiragKumar9 commented on src/main.rs
> +        println!("Setting Overwrite parameter");
I assume this was for debugging purposes. I would remove this print statement now and not have it on main.

2024-12-19 21:06 UTC, ChiragKumar9 commented on src/transmission_manager.rs
> +use crate::contact::ContextContactExt;
Nit: possible to make one `use crate::{}` import statement? I find that easier to read.

2024-12-19 21:06 UTC, ChiragKumar9 requested changes
Please also update the readme with the new syntax for running the model.

2024-12-20 02:13 UTC, ChiragKumar9 approved these changes

2024-12-20 02:13 UTC, ChiragKumar9 commented on src/main.rs
> +    ///Whether force overwrite of output files if they already exist
```suggestion
    /// Whether to force overwrite of output files if they already exist.
```

2024-12-20 17:24 UTC, k88hudson-cfa approved these changes
LGTM

2024-12-20 17:24 UTC, k88hudson-cfa commented on src/main.rs
> +    #[arg(short = 'f', long)]
This will be `f` by default (you can just include `short`)

2024-12-20 17:27 UTC, merged