Design document: natural history manager
CDCgov/ixa-epi-isolation pull request #36
Opened 2024-12-30 18:53 UTC by ChiragKumar9

2025-01-02 20:48 UTC, confunguido requested changes

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
> +Most ABMs are calibrated to counts from clinical data, such as the number of people who are
I don't think we need that much context on this. Try to keep it simple.

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
> +## Application to isolation guidance
I would move this higher in the document.

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
> +        assign_natural_history(self, person_id);
I don't think we should assign natural history like this. Shouldn't these be two different processes? For instance, once infected, pick a natural history curve, then when scheduling infections look into this method. Question is how to connect this to transmission.rs

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
> +        // Convert from uniform space to real time.
Given that this is markdown, code comments seem redundant

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
As I read this document, the flow of the processes isn't clear.  I would appreciate an algorithm description that mentions for instance when the natural history is initialized, when an infection attempt is made, etc.

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
> +    // Is the person going from S --> I?
These comments are unnecessary, and wrong.

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
> +    if event.current == InfectiousStatusType::Infectious {
See my other comment about whether these should be two separate processes: assign parameters and schedule next infection attempt.

2025-01-02 20:48 UTC, confunguido commented on docs/natural_history_manager.md
> +To ensure that an agent's natural history parameters are not being changed in the middle of their
This kinda makes me think that they should be separate processes. They do different things.

2025-01-07 02:22 UTC, ChiragKumar9 commented on docs/natural_history_manager.md
> +When the `time_to_next_infection_attempt` method is called for the first time, it needs to set the
We discussed that the index assignment should be lazy, and it makes sense to group it into getting the parameter value because the two must always be called together.

2025-01-10 02:49 UTC, ChiragKumar9 commented on docs/natural_history_manager.md
> +fn schedule_next_infection_attempt(
done

2025-01-10 02:50 UTC, ChiragKumar9 commented on docs/natural_history_manager.md
> +    if event.current == InfectiousStatusType::Infectious {
I believe what you are suggesting favors an explicit assignment of natural history parameters. I don't think that's necessary as it just pushes more code (and the potential to forget it) to the calling module for `get_parameter_value()`. Happy to discuss if I am misunderstanding.

2025-01-10 21:17 UTC, KOVALW requested changes
This is much improved over having this functionality in the transmission manager and I like the schema in general. There are a couple of changes to consider, particularly with reading in the parameter values.

2025-01-10 21:17 UTC, KOVALW commented on docs/natural_history_manager.md
> +### A general pattern for getting parameter values
This is a sufficiently simpler explanation of how `NaturalHistoryParameterValue` can be either scalar or vector and the treatment of each that it might be worthwhile to bring this up earlier to prime the reader for following `time_to_next_infection_attempt`

2025-01-10 21:17 UTC, KOVALW commented on docs/natural_history_manager.md
> +the vector in the hash map for a specified natural history parameter. Indeces are assigned based on
indices or indexes (the latter works better as multiple assignments of an individual label), not indeces

2025-01-10 21:17 UTC, KOVALW commented on docs/natural_history_manager.md
> +    weights: Vec<f64>,
I'm concerned that weights across sets of `NaturalHistoryParameterValues` would restrict the case of user-defined distributions for calling the parameters. Would these still need to be defined in the HashMap even though they would be global values (or at least group values) for defining the rulesets for individual draws during runtime? I'm thinking that if that's the case you waste a lot of CSV input rows on repeat values.

2025-01-10 21:17 UTC, KOVALW commented on docs/natural_history_manager.md
> +infection because these parameters are not present in their parameter set. Therefore, this input
Information by omission seems like a great way to have hidden bugs in the preprocessing steps. I'd rather see a value that ixa-epi-isolation interprets as asymptomatic (None) so that we know the inputs were correctly generated

2025-01-24 02:55 UTC, closed without merging